### ISSUE TITLE
Port the project to latest django version.

### ISSUE THREAD

**Issue by vshelke** [vshelke/bookpro#11]
Currently the application uses `Django==1.11.15`. 
Migrate the whole project without breaking changes to latest django version `Django==2.1.2`.

**Comment by s-surineni** [comment]
The latest version I could find was 2.0.9

**Comment by vshelke** [comment]
@s-surineni `pip install django` gives you the latest version 2.1.2 .

**Comment by s-surineni** [comment]
![django](https://user-images.githubusercontent.com/1143331/47170771-80eb7c80-d324-11e8-832a-4b73d4398b0b.png)

**Comment by vshelke** [comment]
@s-surineni I think you are using Python 2.x. Install with Python 3.x `pip3 install Django`

**Comment by s-surineni** [comment]
I am getting Bad Request (400) error, when I run the server. Do I need to do any extra steps?

I did the following in order

- cloned the project
- created virtual environment `python3 -m venv book_env`
- activated virtual environment
- installed requirements `pip install -r requirements.txt`
- ran the server `./manage.py runserver 8080`
