### ISSUE TITLE
Improve search results

### ISSUE THREAD

**Issue by vshelke** [vshelke/bookpro#31]
Currently when a book is searched there are many related book that come up in the results and the relevant ones are pushed back due to sorting by price.

Eg:-
![screenshot_2018-10-22_at_12 12 23_am](https://user-images.githubusercontent.com/15365654/47270933-6fa6a800-d590-11e8-95d4-f52f53be29a3.jpg)

Come up with a solution where the exact results are shown first and the related results are shown in a subsequent section with heading `Related Books`

Type:
- [ ] Bug
- [ ] New Feature
- [X] Improvement

Pointers to start with:
* [In this file](https://github.com/vshelke/bookpro/blob/master/bookpro/find_books/views.py) the `search` function is responsible for getting the data from sources.
* Check the `all_items` and `relevant` variables values and render them accordingly in the template `find_books/results.html` in different sections.

**Comment by CometS1** [comment]
I'll take a look into this. How do you want the books to be sorted? Do you want it to be sorted based on which are more relevant or do you want the first (or first few) to be the most relevant and afterwards be based on prices?

**Comment by vshelke** [comment]
Thank you @CometS1 for looking into this issue. We would like to :-
Firstly, Show the relevant ones 
Secondly, Show the related ones

Both the sections to be sorted by price.

**Comment by CometS1** [comment]
Wait, I'm confused. I'm assuming that by sorting by price the cheaper books would show first, and it would be impossible to how the relevant ones be first if it is also sorted by price, because if the book is more expensive then it would be put at the end. Would you perhaps want a toggle between both relevant and price for searching?

**Comment by vshelke** [comment]
There are two variables in the search function `all_items` variable which has all the books and `relevant` variable which has only the relevant books. 

As they both are passed to the jinja template `results.html` only the `all_items` variable is used to show the results currently.

You have the relevant variable available in jinja template already. You have to show the contents of relevant variable it in an another section without the books getting repeated.

You can check the file [here](https://github.com/vshelke/bookpro/blob/master/bookpro/find_books/views.py)

**Comment by CometS1** [comment]
I've been trying to setup using Docker and when I try to use the [docker run -it -v $(pwd)/bookpro:/app -p 8080:8080 bookpro] command, it says that the mount is denied and the source path doesn't exist and is not known to Docker. Do you know how to fix that?

**Comment by vshelke** [comment]
Hi @CometS1 It seems to be the path problem in windows. You can retry the command with `docker run -it -v /$(pwd)/bookpro:/app -p 8080:8080 bookpro` by adding an extra slash before `$(pwd)`. For more [info](https://stackoverflow.com/questions/50608301/docker-mounted-volume-adds-c-to-end-of-windows-path-when-translating-from-linux)

**Comment by CometS1** [comment]
I added the slash and it says "/usr/bin/env: ‘python\r’: No such file or directory".

**Comment by vshelke** [comment]
Can you post some screenshots of logs

**Comment by CometS1** [comment]
![image](https://user-images.githubusercontent.com/25065296/47368298-5fd1b580-d6af-11e8-9f01-4d18f81d4dfe.png)

**Comment by CometS1** [comment]
I solved the issue, solution here #36
