### ISSUE TITLE
Add price range filter

### ISSUE THREAD

**Issue by vshelke** [vshelke/bookpro#33]
Add a new price filter widget in the template `find_books/results.html` to be able to filter the books 
according to the price range.
The placement of the filter can be near the top search bar in `results.html` page or any other place you find it perfect.

Note:- You can use any library you like or can come up with a custom implementation to learn.

**Comment by leandrovianna** [comment]
I can take this.

**Comment by vshelke** [comment]
Great @leandrovianna go ahead 👍
