### ISSUE TITLE
Add Google style Python docstrings to functions

### ISSUE THREAD

**Issue by vshelke** [vshelke/bookpro#34]
The code in the repository has to be documented in accordance with the [Google style](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) docstrings.

You can take any one of the files below and start documenting.

Areas Covered:
- [x] `find_books/views.py`(@Hax7 )
- [ ]  `find_books/integrations/amazon.py`
- [ ]  `find_books/integrations/flipkart.py`
- [ ]  `find_books/integrations/infibeam.py`

**Comment by vshelke** [comment]
Yes sure @Hax7 go ahead. 👍

**Comment by Hax7** [comment]
@vshelke so I can only work one file and left the others for other people? I will do the first one "find_books/views.py" then

**Comment by Hax7** [comment]
and if you could please assign it for me

**Comment by vshelke** [comment]
@Hax7 yes sure you can complete the first one itself.

**Comment by Hax7** [comment]
@vshelke ok, good

**Comment by vshelke** [comment]
Hi @aitorres you can go ahead with the remaining files 👍
