### ISSUE TITLE
Add new integration for booksmela.com

### ISSUE THREAD

**Issue by vshelke** [vshelke/bookpro#35]
## Overview
BookPro integrations are python classes inherited from thread class. These classes make request to the given endpoint and parse a list of books in a dictionary which is later used for further processing of results. These integrations help the BookPro to extend its search area to other websites. 

The already implemented integrations for some major sites are available [here](https://github.com/vshelke/bookpro/tree/master/bookpro/find_books/integrations).

### Booksmela Integration specs
* `url = https://www.booksmela.com/catalogsearch/result/?q=<QUERY_HERE>` without angle brackets.
* Refer [BeautifulSoup Implementation](https://github.com/vshelke/bookpro/blob/master/bookpro/find_books/integrations/infibeam.py)
* `data` dictionary
```python
data = {
    'title': '',
    'author': '',
    'offer_link': '',
    'link': '',
    'image': '',
    'price': None,
    'ISBN': '',
    'provider': ''
}
```

### Steps
* Create file in `find_books/integrations/booksmela.py`
* Complete the `class BooksMela (Thread)` in `booksmela.py`
* Complete the `parse_product` function to pull the details specified in `data` dictionary from the `soup`.
* Append the parsed items in `self.items`
* In `find_books/integrations/__init__.py` put `from .booksmela import BooksMela`
* Import the class in `find_books/views.py` and use it in the `search` function to test the results.
* Run and check if results are shown.

**Comment by Naveenkhasyap** [comment]
Hi @vshelke 
I like to work on this.

**Comment by vshelke** [comment]
Hi @dixi3 you can work on this issue and @Naveenkhasyap you can take a look at the other issue which i have tagged you in.
