### ISSUE TITLE
Remove the access and secret keys

### ISSUE THREAD

**Issue by vshelke** [vshelke/bookpro#5]
[In this file!](https://github.com/vshelke/bookpro/blob/master/find_books/api/amazon.py). 
Make the key variables `access_key_id` and `secret_key` both to `''` for security reasons.

**Comment by ravitripathi** [comment]
#7

**Comment by ravitripathi** [comment]
#https://github.com/vshelke/bookpro/commit/cae83079cd78f251286cce937eaeb3b9ac367fc9 #

**Comment by vshelke** [comment]
cool
